fix(build/spdk): "undefined reference to strlcpy"
This fixes an error with a missing dependency on ubuntu.

Signed-off-by: Karl Bonde Torp <k.torp@samsung.com>